[project]
name = "hydra-somewhat-advanced"
version = "0.1.0"
description = ""
authors = [{ name = "Thomas M Kehrenberg", email = "tmke8@posteo.net" }]
requires-python = ">=3.11,<4"
dependencies = [
    "omegaconf==2.4.0.dev11",
    "hydra-core==1.4.0.dev1",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.11"
reportMissingTypeArgument = "none"
reportUnnecessaryComparison = "none"
reportCallInDefaultInitializer = "warning"
reportPropertyTypeMismatch = "warning"
reportUninitializedInstanceVariable = "warning"
reportPrivateUsage = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"
reportConstantRedefinition = "warning"
# these errors are a bit annoying
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
venvPath = "."
venv = ".venv"
